<?php

/**
 * Implements hook_FROM_ID_alter().
 */
function google_one_tap_roles_sync_form_google_one_tap_settings_form_alter(&$form, &$form_state, $form_id) {
  // Load library.
  $info = libraries_load('google-api-php-client');
  if (!$info['loaded']) {
    drupal_set_message(t("Can't authenticate with google as library is missing check Status report or Readme for requirements"), 'error');
    return FALSE;
  }

  // Get all groups.
  $client = gauth_client_get(variable_get('gauth_name'), FALSE);
  $service = new Google_Service_Directory($client);
  $result = $service->groups->listGroups(['domain' => variable_get('domain')]);
  $g_groups = $result->getGroups();
  $groups = [];
  foreach ($g_groups as $group) {
    $groups[$group->getName()] = $group->getName();
  }

  $form['settings']['domain']['sync_roles'] = array(
    '#type' => 'checkbox',
    '#title' => t('Sync roles'),
    '#default_value' => variable_get('sync_roles', FALSE),
    '#description' => t('Use this option if you want to sync roles from Google into Drupal.'),
    '#states' => array(
      'visible' => array(
        ':input[name="use_domain"]' => array('checked' => TRUE),
      ),
    ),
  );
  $form['settings']['domain']['roles_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Roles'),
    '#description' => t('In select field are displayed roles from Drupal, in label is displayed group from Google.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#states' => array(
      'visible' => array(
        ':input[name="sync_roles"]' => array('checked' => TRUE),
        ':input[name="use_domain"]' => array('checked' => TRUE),
      ),
    ),
  );

  // Get all roles.
  $roles = user_roles();
  $options = array();
  foreach ($roles as $role) {
    if ($role != 'anonymous user') {
      $options[$role] = $role;
    }
  }
  if (!empty($groups)) {
    foreach ($groups as $group) {
      $form['settings']['domain']['roles_fieldset']['group_' . $group] = array(
        '#type' => 'select',
        '#title' => $group,
        '#default_value' => variable_get('group_' . $group, ''),
        '#options' => $options,
      );
    }
  }
  $form['#submit'][] = 'google_one_tap_roles_sync_submit_form';
}

/**
 * Implements hook_FORM_ID_submit().
 */
function google_one_tap_roles_sync_submit_form($form, &$form_state) {
  $values = $form_state['values'];
  variable_set('sync_roles', $values['sync_roles']);

  foreach ($values as $key => $value) {
    if (strpos($key, 'group_') === 0) {
      variable_set($key, $value);
    }
  }
}

/**
 * Implements hook_data_alter().
 */
function google_one_tap_roles_sync_google_one_tap_new_user_alter(&$edit) {
  // Get client.
  $client = gauth_client_get(variable_get('gauth_name'), FALSE);
  $service = new Google_Service_Directory($client);
  // Load all groups.
  $result = $service->groups->listGroups(['domain' => variable_get('domain')]);
  $g_groups = $result->getGroups();

  // Go through each group.
  foreach ($g_groups as $group) {
    // Get all members of this group.
    $group_members = $service->members->listMembers($group->getId());
    $members = $group_members->getMembers();
    // Go trough each member in this group.
    foreach ($members as $member) {
      // Check if this member exist in group.
      if ($member->getEmail() == $edit['mail']) {
        // Check if we have set role for this group.
        if ($g_role = variable_get('group_' . $group->getName())) {
          // Check if role is not anonymous or authenticated,
          // because authenticated is default variable which is getting added
          // automatically.
          if ($g_role != 'anonymous user' && $g_role != 'authenticated user') {
            // Load role.
            $role = user_role_load_by_name($g_role);
            // Check if user doesn't have this role.
            if ($edit['roles'][$role->rid] != $g_role) {
              // Add role to user.
              $edit['roles'][$role->rid] = $role->name;
              break;
            }
          }
        }
      }
    }
  }
}

